### ISSUE TITLE
OP_SHA256

### ISSUE THREAD

**Issue by jrick** [decred/atomicswap#40]
Now that the new OP_SHA256 rules have been activated in Decred, all of the atomic swap tools should switch over to this more secure hash function.  They are currently using OP_RIPEMD160 due to the sha256 opcode not having been available in the Decred scripting vm.

Before this can be completed, all of the txscript packages must be updated to recognize the OP_SHA256 version of the atomic swap contract: 

- [x] btcd/txscript (btcsuite/btcd#1085)
- [x] dcrd/txscript (decred/dcrd#930)
- [x] ltcd/txscript (https://github.com/jrick/btcd/commit/07a02d6ef2b1822aad5856cb8cbd2fa6eebb14a8)
- [x] partd/txscript (particl/partsuite_partd#1)
- [x] vtcd/txscript (vertcoin/vtcd#2)

@dasource @metalicjames heads up, I'll be creating some PRs for your projects for this change.

**Comment by DesWurstes** [comment]
TODO: After the required pull requests are merged, it needs `dep ensure -update`

**Comment by devwarrior777** [comment]
Hi,
Is it just the one vendor change please?
		//gf:future->
		// pops[1].opcode.value == OP_SHA256 &&
		// pops[2].opcode.value == OP_DATA_32 &&
		pops[1].opcode.value == OP_RIPEMD160 &&
		pops[2].opcode.value == OP_DATA_20 &&
		//<-gf
                ...

Thanks

**Comment by jrick** [comment]
The links in the issue description contain the diffs for the changes.  In addition to these changes, the atomicswap tools themselves must also be updated to create contract scripts using SHA256-hashed secrets.

**Comment by metalicjames** [comment]
@jrick Apologies for the delay, I must've missed the notification for your pull request into vtcd. Merged now.
